export const IpcChannels = {
  appStatus: 'app:status',
  setApiKey: 'app:setApiKey',
  clearApiKey: 'app:clearApiKey',
  setSubscriptionToken: 'app:setSubscriptionToken',
  clearSubscriptionToken: 'app:clearSubscriptionToken',
  setAuthMode: 'app:setAuthMode',
  openObservatory: 'app:openObservatory',
  observatoryFocusTask: 'observatory:focusTask',
  shellNavigate: 'shell:navigate',
  openPalette: 'app:openPalette',
  resizePalette: 'app:resizePalette',
  openExternal: 'app:openExternal',

  showAnswerHud: 'hud:show',
  hideAnswerHud: 'hud:hide',
  resizeAnswerHud: 'hud:resize',
  setAnswerHudInteractive: 'hud:setInteractive',
  answerHudTrack: 'hud:track',

  listSkills: 'skills:list',
  refreshSkills: 'skills:refresh',
  writeSkillBody: 'skills:writeBody',
  createSkill: 'skills:create',
  deleteSkill: 'skills:delete',
  revealSkill: 'skills:reveal',

  listMcpServers: 'mcp:list',
  listClaudeMcps: 'mcp:listClaude',
  addMcpServer: 'mcp:add',
  removeMcpServer: 'mcp:remove',
  setMcpDisabled: 'mcp:setDisabled',
  readMcpFile: 'mcp:readFile',
  writeMcpFile: 'mcp:writeFile',
  revealMcpFile: 'mcp:revealFile',
  probeMcpTools: 'mcp:probeTools',
  invokeMcpTool: 'mcp:invokeTool',

  listModules: 'modules:list',
  dispatchIntent: 'modules:dispatchIntent',
  setModuleEnabled: 'modules:setEnabled',
  writeModuleSettings: 'modules:writeSettings',
  modulesChanged: 'modules:changed',

  listJarvisDir: 'fs:listJarvisDir',
  readJarvisFile: 'fs:readJarvisFile',
  writeJarvisFile: 'fs:writeJarvisFile',

  listProjects: 'projects:list',
  createProject: 'projects:create',
  updateProject: 'projects:update',
  deleteProject: 'projects:delete',
  setActiveProject: 'projects:setActive',
  setProjectInboxScan: 'projects:setInboxScan',
  projectsChanged: 'projects:changed',
  listProjectTemplates: 'projects:listTemplates',
  listProjectMemory: 'projects:listMemory',
  readProjectMemory: 'projects:readMemory',
  writeProjectMemory: 'projects:writeMemory',
  deleteProjectMemory: 'projects:deleteMemory',
  deleteNoteEntry: 'notes:deleteEntry',
  setNoteEntryArchived: 'notes:setEntryArchived',

  readPreferences: 'preferences:read',
  writePreferences: 'preferences:write',
  revealPreferences: 'preferences:reveal',
  preferencesChanged: 'preferences:changed',

  readNotificationPrefs: 'notif:read',
  writeNotificationPrefs: 'notif:write',
  notificationPrefsChanged: 'notif:changed',

  readInboxPrefs: 'inboxPrefs:read',
  writeInboxPrefs: 'inboxPrefs:write',
  inboxPrefsChanged: 'inboxPrefs:changed',

  openInClaudeDesktop: 'tasks:openInClaudeDesktop',
  costSummary: 'tasks:costSummary',
  pickDirectory: 'fs:pickDirectory',

  httpApiStatus: 'http:status',
  rotateHttpApiToken: 'http:rotateToken',

  listInbox: 'inbox:list',
  listInboxDismissed: 'inbox:listDismissed',
  listInboxSources: 'inbox:listSources',
  revealInboxFile: 'inbox:revealFile',
  refreshInbox: 'inbox:refresh',
  inboxChanged: 'inbox:changed',
  inboxRefreshing: 'inbox:refreshing',
  dismissInboxItem: 'inbox:dismiss',
  restoreInboxItem: 'inbox:restore',
  countInboxSource: 'inbox:countSource',
  clearInboxSource: 'inbox:clearSource',
  meetingImminent: 'inbox:meetingImminent',
  suppressMeetingPrompt: 'inbox:suppressMeetingPrompt',

  readDashboard: 'dashboard:read',
  writeDashboard: 'dashboard:write',
  dashboardChanged: 'dashboard:changed',

  listBriefingKinds: 'briefings:listKinds',
  listBriefingFiles: 'briefings:listFiles',
  readBriefingFile: 'briefings:readFile',
  writeBriefingFile: 'briefings:writeFile',
  generateBriefing: 'briefings:generate',
  briefingsChanged: 'briefings:changed',
  readSkillBody: 'skills:readBody',

  requestMicAccess: 'media:requestMic',
  micStatus: 'media:micStatus',

  transcribeAudio: 'audio:transcribe',
  transcribeProgress: 'audio:progress',

  meetingStart: 'meeting:start',
  meetingStopRequest: 'meeting:stop-request',
  meetingFinish: 'meeting:finish',

  listRoutines: 'routines:list',
  saveRoutine: 'routines:save',
  deleteRoutine: 'routines:delete',
  runRoutineNow: 'routines:runNow',
  routinesChanged: 'routines:changed',

  routePrompt: 'palette:routePrompt',
  previewIntent: 'palette:previewIntent',

  listSkillSuggestions: 'skill-suggestions:list',
  acceptSkillSuggestion: 'skill-suggestions:accept',
  dismissSkillSuggestion: 'skill-suggestions:dismiss',
  removeSkillSuggestion: 'skill-suggestions:remove',
  skillSuggestionsChanged: 'skill-suggestions:changed',

  listReminders: 'reminders:list',
  cancelReminder: 'reminders:cancel',
  removeReminder: 'reminders:remove',
  fireReminderNow: 'reminders:fireNow',
  markReminderDone: 'reminders:markDone',
  remindersChanged: 'reminders:changed',

  launchTask: 'task:launch',
  launchShell: 'task:launchShell',
  abortTask: 'task:abort',
  sendTaskMessage: 'task:sendMessage',
  listTasks: 'task:list',
  getTaskHistory: 'task:getHistory',

  taskEvent: 'task:event',
  taskStatus: 'task:status',
  taskRemoved: 'task:removed',

  listActivity: 'activity:list',
  activityChanged: 'activity:changed',
} as const;

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels];
